# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: foreign_key_migrations_example
  username: root
  password: ""
  
test:
  adapter: mysql
  database: foreign_key_migrations_example_test
  username: root
  password: ""